site_name: Tech Docs
site_url: https://mk-next.github.io/tech-docs
nav:
  - Início: index.md
  - Processos:
      - Fluxo de Deploy: process/deploy.md
  - Decisões Técnicas:
      - Estratégia de Autenticação: decisions/auth.md
theme:
  name: material